---
- name: Playbook de Actualizacion de Windows
  hosts: all
  gather_facts: yes
  tasks:
    - name: Instalar parches directo desde Microsoft Update
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        server_selection: microsoft_update  # <--- ESTA ES LA MAGIA
        state: installed
        reboot: yes
